project-checkers: [unittest]
file-checkers:
  '*.py': [pylint, pep8, pep257]
  '*.rst': rst-lint
  'tests/*.py':
    - pylint: {rcfile: tests/pylintrc}
  'scripts/*.py': []
config: 
  pylint: {accepted-code-rate: 9}
